spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: username
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        show_sql: true
        format_sql: true

                    ##LIQUIBASE PROPERTIES
  liquibase:
    change-log: liquibase/changelog-master.yml